format = """
$directory\
$git_branch\
$git_status\
$java\
$line_break$character"""

palette = 'jacob'

[palettes.jacob]
color_aqua = '#4cadfb'
color_green = '#7ed232'
color_red = '#eb3a17'
color_yellow = '#d1b02c'
color_purple = '#bd00ff'

[directory]
truncation_length = 20
truncate_to_repo = false
format = "[ $path ](bold color_aqua)"

[git_branch]
symbol = ""
format = 'on [$symbol $branch ](color_green)'

[git_status]
ahead = '⇡${count}(color_green) '
behind = '⇣${count}(color_green) '
untracked = '?${count}(color_red) '
stashed = '*${count}(color_green) '
modified = '!${count}(color_yellow) '
staged = '+${count}(color_green) '
format = '[($ahead_behind$untracked$stashed$modified$staged )]($style)'

[java]
format = '[${symbol}${version}](color_purple)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](fg:color_green)'
error_symbol = '[](fg:color_red)'
vimcmd_symbol = '[](fg:color_green)'
vimcmd_replace_one_symbol = '[](fg:color_purple)'
vimcmd_replace_symbol = '[](fg:color_purple)'
vimcmd_visual_symbol = '[](fg:color_yellow)'
